<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\..\..\Shared\Memoria.Shared.Infrastructure\Memoria.Shared.Infrastructure.csproj" />
      <ProjectReference Include="..\..\..\Shared\Memoria.Shared.Kernel\Memoria.Shared.Kernel.csproj" />
      <ProjectReference Include="..\Memoria.Cards.Contracts\Memoria.Cards.Contracts.csproj" />
    </ItemGroup>

</Project>
