<Project Sdk="Microsoft.NET.Sdk.Web">

    <ItemGroup>
        <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
        <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
        <PackageReference Include="Serilog.Formatting.Compact" Version="3.0.0" />
        <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
        <PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>

        <PackageReference Include="MediatR" Version="12.4.1" />
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.10.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Memoria.Api\Memoria.Api.csproj" />
      <ProjectReference Include="..\Memoria.Bot\Memoria.Bot.csproj" />
      <ProjectReference Include="..\Modules\Cards\Memoria.Cards.Contracts\Memoria.Cards.Contracts.csproj" />
      <ProjectReference Include="..\Modules\Cards\Memoria.Cards\Memoria.Cards.csproj" />
      <ProjectReference Include="..\Modules\Reviews\Memoria.Reviews\Memoria.Reviews.csproj" />
      <ProjectReference Include="..\Modules\Reminders\Memoria.Reminders.Contracts\Memoria.Reminders.Contracts.csproj" />
      <ProjectReference Include="..\Modules\Reminders\Memoria.Reminders\Memoria.Reminders.csproj" />
      <ProjectReference Include="..\Modules\Reviews\Memoria.Reviews.Contracts\Memoria.Reviews.Contracts.csproj" />
      <ProjectReference Include="..\Modules\Users\Memoria.Users.Contracts\Memoria.Users.Contracts.csproj" />
      <ProjectReference Include="..\Modules\Users\Memoria.Users\Memoria.Users.csproj" />
      <ProjectReference Include="..\Shared\Memoria.Shared.Infrastructure\Memoria.Shared.Infrastructure.csproj" />
      <ProjectReference Include="..\Shared\Memoria.Shared.Kernel\Memoria.Shared.Kernel.csproj" />
    </ItemGroup>

</Project>
