<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\..\..\Shared\Memoria.Shared.Kernel\Memoria.Shared.Kernel.csproj" />
      <ProjectReference Include="..\..\Cards\Memoria.Cards.Contracts\Memoria.Cards.Contracts.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MediatR.Contracts" Version="2.0.1" />
    </ItemGroup>

</Project>
